### ISSUE TITLE
Registered with email will receive "404 not found" link in second verification email

### ISSUE THREAD

**Issue by skmisaac** [likecoin/liker-land#227]
User registered from liker.land via email and verified through authcore's verification code, and completed the registration process. He then received an additional email from like.co asking for email verification. The link provided by the 2nd verification email results in a 404.

Expected: Should not verify an email twice, should not result in 404 in verification link.

Current: After registration with email and verified. An extra verification email was sent with link results in 404

**Comment by williamchong007** [comment]
This is due to outdated id token from authcore register widget
should be fixed by https://github.com/likecoin/like-co/pull/1377
