### ISSUE TITLE
The format in reset password notification email

### ISSUE THREAD

**Issue by edmondyu** [likecoin/liker-land#285]
1) should change the bold face of "Hi" back to normal text style, and to "Dear Liker,"
2) The words in banner is distorted under dark mode

![IMG_1088 2](https://user-images.githubusercontent.com/17264698/90846428-afac6100-e39a-11ea-9236-4992726daffc.PNG)

**Comment by williamchong** [comment]
Should be fixed in authcore settings some time ago
