### ISSUE TITLE
grammatical and other minor issues with new home page

### ISSUE THREAD

**Issue by ckxpress** [likecoin/liker-land#503]
1. should be "Earn as you write. Collect as you read." (punctuation) <img width="1009" alt="Screenshot 2022-07-28 at 1 15 41 AM" src="https://user-images.githubusercontent.com/7088918/181309227-8701f5fc-ee88-4c96-9735-94b580cb106c.png">
2. so is it "Earn as you write" or "Publish as you write", or intentionally use both? if you ask me, "Publish" is much better.
3. embedded into any website - suggest to use "webpage" instead of "website"
4. Everyone can sell their work - "everyone" is singular
5. Collect to showcase an individual’s readership and authorship - i'm not sure i understand. Collect is for readers right? so not supposed to showcase authorship? anyway, just let you know my perception reading it.
6. Publish any website as NFT - suggest to use "webpage" instead of "website"
7. Writers can turn creative works and URLs into NFTs - suggest: Writers can also turn any webpage into NFT
8. Each Writing NFT will automatically increase in price after each NFT is collected. - suggest: Price will automatically increase as demand goes up.
9. you can directly install the free LikeCoin plugin from the [WordPress plugins](https://wordpress.org/plugins/likecoin/) - suggest: you may directly install the free [LikeCoin plugin](https://wordpress.org/plugins/likecoin/
10. footers become chinese -  加入社群 [關於 Liker Land](https://liker.land/about)
11. 關於我們 [關於 LikeCoin](https://like.co/) [讚賞公民](https://liker.land/civic)

**Comment by phoebepoon** [comment]
2. let's use "Publish as you write"
5. Remove the word "collect". So the sentence will become "Showcase an individual’s readership and authorship with a verifiable ownership record."

**Comment by ckxpress** [comment]
7.  Writers can turn creative works and URLs into NFTs - suggest: Writers can also turn any webpage into NFT

missed an "an", solly.
Writers can also turn any webpage into an NFT
