### ISSUE TITLE
collect & transfer error

### ISSUE THREAD

**Issue by ckxpress** [likecoin/liker-land#598]
whenever i collect (my own) NFT and transfer to others, this error message comes, before i refresh (sometimes a few times) and try again and succeed. not sure it's about delay, or must at least refresh once, or both, or what.

<img width="560" alt="Screenshot 2022-09-06 at 10 26 42 PM" src="https://user-images.githubusercontent.com/7088918/188805474-a518e217-594f-480f-80ce-123e64ce8bc7.png">

**Comment by nwingt** [comment]
@ckxpress A significant update was released yesterday, is this issue still exist?

**Comment by nwingt** [comment]
Probably relates to [this](https://github.com/nwingt/liker-land/blob/33ba999ba6d330dee3e95ad512cecf96c1ecac67/src/mixins/nft.js#L150-L153)

**Comment by ckxpress** [comment]
@nwingt yes same in new UI
<img width="541" alt="Screenshot 2022-09-07 at 11 36 04 PM" src="https://user-images.githubusercontent.com/7088918/189051958-7f10b28d-6888-4f81-97c3-129f17ee22b7.png">

**Comment by nwingt** [comment]
@ckxpress It has been fixed, please check.
