### ISSUE TITLE
throw error when connecting with Cosmostation in Chrome

### ISSUE THREAD

**Issue by ckxpress** [likecoin/liker-land#649]
says validation error, ChainID contains an invalid value.

<img width="1369" alt="Screenshot 2022-09-20 at 12 44 03 PM" src="https://user-images.githubusercontent.com/7088918/191352749-0343bc13-1311-484b-97a0-2902cdb47a2d.png">

on Brave, connect with Cosmostation is fine. 

but when i use depub.space, failed to connect due to the same error (it shows the error to users on UI) in both browsers.

i once added LikeCoin chain manual on Cosmostation in Brave.

while in Chrome Cosmostation was a fresh installation.

**Comment by nwingt** [comment]
Have you enabled the LikeCoin chain?
<img width="361" alt="image" src="https://user-images.githubusercontent.com/17264716/191426068-677c86de-47c6-49d9-9cc4-3d0ac23cc8fb.png">

**Comment by ckxpress** [comment]
yup

**Comment by nwingt** [comment]
@ckxpress Should be fixed
