### ISSUE TITLE
[查看精選作品] button not clickable

### ISSUE THREAD

**Issue by ckxpress** [likecoin/liker-land#932]
https://liker.land/writing-nft/about

**Comment by williamchong** [comment]
> https://liker.land/writing-nft/about

it's clickable on my side, can you try again, we did just have some js breaking bug which is fixed
if not, please provide a screenshot, device you are on, and if there is any console error

**Comment by ckxpress** [comment]
did you try Chinese interface? for me, it's clickable on eng interface but not chi

**Comment by williamchong** [comment]
> did you try Chinese interface? for me, it's clickable on eng interface but not chi

Cant reproduce the issue on both language, what device, os and browser version are you on?

**Comment by ckxpress** [comment]
for me - M1, Mac OS 13.1 (22C65) - [查看精選作品] only works when i use Safari, but not Chrome/Brave/Firefox

**Comment by williamchong** [comment]
@ckxpress please check if it's fixed, thanks

**Comment by ckxpress** [comment]
yes thanks.
